services:
  - type: web
    name: mymotion-api
    runtime: docker
    plan: free
    region: singapore # hoặc oregon, ohio, frankfurt
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DOTNET_USE_POLLING_FILE_WATCHER
        value: "true"
      - key: DATABASE_URL
        sync: false # Nhập tay trên Dashboard để bảo mật
      - key: SENDER_ID
        sync: false
      - key: RECEIVER_ID
        sync: false
